version: '3.3'
services:
  post_db:
    image: mongo:latest
    container_name: ${DB_NAME}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USER_NAME}/ui:1.0
    container_name: ${UI_NAME}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5001:5001"
    networks:
      - reddit
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    build: ./comment
    image: ${USER_NAME}/comment:1.0
    container_name: ${COMMENT_NAME}
    networks:
      - reddit
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9091:9091'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - reddit
      - front_net
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' #

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - reddit
      - front_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
  front_net:
