all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./id_rsa
  children:
    k8s-masters:
      hosts:
        master:
          ansible_host: 158.160.101.140
          ansible_port: 22
    k8s-nodes:
      hosts:
        node-0:
          ansible_host: 158.160.99.181
          ansible_port: 22
        node-1:
          ansible_host: 62.84.124.147
          ansible_port: 22
        node-2:
          ansible_host: 158.160.123.125
          ansible_port: 22
