---
- name: Install useful packages
  ansible.builtin.apt:
    pkg:
      - net-tools
      - jq
      - python3
      - python-is-python3
    state: present
    update_cache: true

- name: Get envplate tool
  ansible.builtin.unarchive:
    src: https://github.com/kreuzwerker/envplate/releases/download/v1.0.2/envplate_1.0.2_Linux_x86_64.tar.gz
    include:
      - envplate
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
    remote_src: true
    creates: /usr/local/bin/envplate

- name: Add envplate symlink
  ansible.builtin.file:
    src: /usr/local/bin/envplate
    dest: /usr/bin/envplate
    owner: root
    group: root
    mode: "0755"
    state: link
  when: not ansible_check_mode

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Modify nofile soft limit for root
  community.general.system.pam_limits:
    domain: root
    limit_type: soft
    limit_item: nofile
    value: 524288

- name: Modify vm.max_map_count
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ sysctl_vm_max_map_count | default(65530) }}"
