---
- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    shell: /bin/bash
    groups: docker
    create_home: true
    append: true
    remove: true
  with_items: "{{ users }}"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', 'files/ssh/users/' + item.name + '.pub') }}"
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
  with_items: "{{ users }}"
  when: item.state == "present"

- name: Add user to sudoers
  community.general.system.sudoers:
    name: "{{ item.name }}"
    user: "{{ item.name }}"
    state: "{% if item.sudo is true %}present{% else %}absent{% endif %}"
    commands: ALL
    nopassword: true
  with_items: "{{ users }}"
