---
- name: Install necessary packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - apt-transport-https
      - software-properties-common
      - net-tools
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker CE
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add docker config
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    src: templates/docker/daemon.json.j2
    mode: "0644"
  notify:
    - Restart Docker

- name: Add ansible user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
    force: true
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  ignore_errors: "{{ ansible_check_mode }}"
